# Generated by Django 2.0.9 on 2019-04-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_donations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='eventId',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='bankDetails',
        ),
        migrations.DeleteModel(
            name='Donations',
        ),
    ]
